# Generated by Django 5.2.2 on 2025-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('motivo_prestamo', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('probabilidad_incumplimiento', models.FloatField()),
                ('score', models.IntegerField()),
                ('ingresos_anuales', models.FloatField(blank=True, null=True)),
                ('deuda_total', models.FloatField(blank=True, null=True)),
                ('historial_credito', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
