# Generated by Django 5.2.2 on 2025-06-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccion',
            name='historial_credito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
