name: Render and Deploy R Markdown

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
    - name: Install R dependencies
      run: |
        R -e "install.packages(c('rmarkdown', 'knitr', 'DT', 'plotly'))"
        
    - name: Render R Markdown
      run: |
        R -e "rmarkdown::render('Trabajo3/reporte/Trabajo 3 Equipo 3 RNAB.Rmd', output_file = 'index.html')"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Trabajo3/reporte 